namespace DisposableEmailShield;

/// <summary>
/// Maintains a HashSet of known disposable/temporary email domains.
/// Sources: aggregated from publicly available disposable email lists.
/// To update: add new domains to the set below.
/// </summary>
public static class DisposableDomains
{
    private static readonly HashSet<string> Domains = new(StringComparer.OrdinalIgnoreCase)
    {
        // --- Major disposable email services ---
        "mailinator.com",
        "guerrillamail.com",
        "guerrillamail.de",
        "guerrillamail.net",
        "guerrillamail.org",
        "guerrillamailblock.com",
        "grr.la",
        "guerrilla.ml",
        "tempmail.com",
        "temp-mail.org",
        "temp-mail.io",
        "throwaway.email",
        "throwaway.com",
        "throam.com",
        "yopmail.com",
        "yopmail.fr",
        "yopmail.net",
        "yopmail.gq",
        "sharklasers.com",
        "guerrillamailblock.com",
        "dispostable.com",
        "trashmail.com",
        "trashmail.me",
        "trashmail.net",
        "trashmail.org",
        "trashmail.io",
        "trash-mail.com",
        "fakeinbox.com",
        "fakemail.net",
        "mailnesia.com",
        "maildrop.cc",
        "mailcatch.com",
        "mailexpire.com",
        "mailforspam.com",
        "mailnull.com",
        "mailsac.com",
        "mailscrap.com",
        "mailshell.com",
        "mailslurp.com",
        "mailtemp.info",
        "mailzilla.com",
        "mintemail.com",
        "mohmal.com",
        "mt2015.com",
        "mytemp.email",
        "mytrashmail.com",
        "nada.email",
        "nada.ltd",
        "nowmymail.com",
        "nwytg.net",
        "objectmail.com",
        "odaymail.com",
        "one-time.email",
        "otherinbox.com",

        // --- 10minutemail and variants ---
        "10minutemail.com",
        "10minutemail.co.za",
        "10minutemail.de",
        "10minutemail.net",
        "10minutemail.pl",
        "10mail.org",
        "10mail.tk",
        "20minutemail.com",
        "20minutemail.it",
        "20mail.it",
        "20email.eu",
        "20email.it",

        // --- Temp/disposable services ---
        "tempail.com",
        "tempalias.com",
        "tempe4mail.com",
        "tempemail.co.za",
        "tempemail.net",
        "tempinbox.com",
        "tempmaildemo.com",
        "tempomail.fr",
        "temporaryemail.net",
        "temporaryemail.us",
        "temporaryforwarding.com",
        "temporaryinbox.com",
        "temporarymailaddress.com",
        "tempthe.net",
        "tempymail.com",
        "thankdog.com",
        "tmail.ws",
        "tmpmail.net",
        "tmpmail.org",
        "toiea.com",
        "toomail.biz",
        "topranklist.de",

        // --- Spam/guerrilla variants ---
        "spambox.us",
        "spamcero.com",
        "spamcorner.net",
        "spamcowboy.com",
        "spamcowboy.net",
        "spamcowboy.org",
        "spamday.com",
        "spamex.com",
        "spamfighter.cf",
        "spamfighter.ga",
        "spamfighter.gq",
        "spamfighter.ml",
        "spamfighter.tk",
        "spamfree24.com",
        "spamfree24.de",
        "spamfree24.eu",
        "spamfree24.info",
        "spamfree24.net",
        "spamfree24.org",
        "spamgourmet.com",
        "spamgourmet.net",
        "spamgourmet.org",
        "spamherelots.com",
        "spamhereplease.com",
        "spamhole.com",
        "spamify.com",
        "spaminator.de",
        "spaml.com",
        "spaml.de",
        "spammotel.com",
        "spamobox.com",
        "spamoff.de",
        "spamslicer.com",
        "spamspot.com",
        "spamstack.net",
        "spamthis.co.uk",
        "spamtrail.com",
        "spamtrap.ro",

        // --- Burner mail services ---
        "burnermail.io",
        "burnmail.ca",

        // --- Cloaked/anonymous email ---
        "anonymbox.com",
        "anonymail.dk",
        "anonymized.org",
        "anonymousspeech.com",
        "anonbox.net",
        "anonmails.de",
        "ano-mail.net",

        // --- Popular disposable domains (high volume) ---
        "getairmail.com",
        "getnada.com",
        "gishpuppy.com",
        "grandmamail.com",
        "grandmasmail.com",
        "great-host.in",
        "greensloth.com",
        "gufum.com",
        "harakirimail.com",
        "hartbot.de",
        "hatespam.org",
        "hidemail.de",
        "hidzz.com",
        "hotpop.com",
        "hulapla.de",
        "ichimail.com",
        "imails.info",
        "imgof.com",
        "imgv.de",
        "incognitomail.com",
        "incognitomail.net",
        "incognitomail.org",
        "inpwa.com",
        "insorg-mail.info",
        "instant-mail.de",
        "ipoo.org",
        "irish2me.com",
        "iwi.net",
        "jetable.com",
        "jetable.fr.nf",
        "jetable.net",
        "jetable.org",
        "jnxjn.com",
        "jourrapide.com",
        "junk1e.com",
        "junkmail.ga",
        "junkmail.gq",
        "kasmail.com",
        "kaspop.com",
        "keepmymail.com",
        "killmail.com",
        "killmail.net",
        "kingsq.ga",
        "kir.ch.tc",
        "klassmaster.com",
        "klassmaster.net",
        "klzlk.com",
        "koszmail.pl",
        "kurzepost.de",
        "lackmail.net",
        "lags.us",
        "laoho.com",
        "lastmail.co",
        "lastmail.com",
        "lazyinbox.com",
        "letthemeatspam.com",
        "lhsdv.com",
        "lifebyfood.com",
        "link2mail.net",
        "litedrop.com",
        "llogin.ru",
        "logalog.com",
        "lortemail.dk",
        "lovemeleaveme.com",
        "lr78.com",
        "luv2.us",
        "m21.cc",
        "maboard.com",
        "mail-hierarchie.de",
        "mail-temporaire.fr",
        "mail.by",
        "mail.mezimages.net",
        "mail.zp.ua",
        "mail1a.de",
        "mail21.cc",
        "mail2rss.org",
        "mail333.com",
        "mail4trash.com",
        "mailbidon.com",
        "mailblocks.com",
        "mailbucket.org",
        "mailcat.biz",
        "mailcatch.com",
        "mailde.de",
        "mailde.info",
        "maildx.com",
        "maileater.com",
        "mailed.in",
        "mailimate.com",
        "mailin8r.com",
        "mailinater.com",
        "mailinator.net",
        "mailinator.org",
        "mailinator.us",
        "mailinator2.com",
        "mailincubator.com",
        "mailismagic.com",
        "mailmate.com",
        "mailme.ir",
        "mailme.lv",
        "mailme24.com",
        "mailmetrash.com",
        "mailmoat.com",
        "mailms.com",
        "mailnator.com",
        "mailnull.com",
        "mailorg.org",
        "mailpick.biz",
        "mailproxsy.com",
        "mailquack.com",
        "mailrock.biz",
        "mailseal.de",
        "mailsiphon.com",
        "mailslite.com",
        "mailtemp.info",
        "mailtothis.com",
        "mailtrash.net",
        "mailzilla.com",
        "mailzilla.org",

        // --- Widely used throwaway domains ---
        "discard.email",
        "discardmail.com",
        "discardmail.de",
        "disposable.cf",
        "disposable.ga",
        "disposable.ml",
        "disposableaddress.com",
        "disposableemailaddresses.emailmiser.com",
        "disposableinbox.com",
        "dispose.it",
        "disposeamail.com",
        "disposemail.com",
        "dodgeit.com",
        "dodgit.com",
        "dodgit.org",
        "drdrb.com",
        "drdrb.net",
        "dropmail.me",
        "dumpandjunk.com",
        "dumpmail.de",
        "dumpyemail.com",
        "e4ward.com",
        "easytrashmail.com",
        "einmalmail.de",
        "einrot.com",
        "einrot.de",
        "eintagsmail.de",
        "emaildienst.de",
        "emailgo.de",
        "emailias.com",
        "emailigo.de",
        "emailinfive.com",
        "emaillime.com",
        "emailmiser.com",
        "emailproxsy.com",
        "emails.ga",
        "emailsensei.com",
        "emailspam.cf",
        "emailspam.ga",
        "emailspam.gq",
        "emailspam.ml",
        "emailspam.tk",
        "emailtemporanea.com",
        "emailtemporanea.net",
        "emailtemporar.ro",
        "emailtemporario.com.br",
        "emailthe.net",
        "emailtmp.com",
        "emailto.de",
        "emailwarden.com",
        "emailx.at.hm",
        "emailxfer.com",
        "emeil.in",
        "emeil.ir",
        "emz.net",
        "enayu.com",
        "enterto.com",
        "ephemail.net",
        "etranquil.com",
        "etranquil.net",
        "etranquil.org",
        "evopo.com",
        "example.com",
        "explodemail.com",
        "express.net.ua",
        "eyepaste.com",
        "fastacura.com",
        "fastchevy.com",
        "fastchrysler.com",
        "fastkawasaki.com",
        "fastmazda.com",
        "fastmitsubishi.com",
        "fastnissan.com",
        "fastsubaru.com",
        "fastsuzuki.com",
        "fasttoyota.com",
        "fastyamaha.com",
        "filzmail.com",
        "fixmail.tk",
        "fizmail.com",
        "fleckens.hu",
        "flyspam.com",
        "frapmail.com",
        "front14.org",
        "fudgerub.com",
        "fux0ringduh.com",

        // --- Services popular in 2024-2025 ---
        "tempmailo.com",
        "emailondeck.com",
        "emailfake.com",
        "crazymailing.com",
        "mailpoof.com",
        "tempr.email",
        "internxt.email",
        "tmailor.com",
        "tempmail.ninja",
        "tempmail.plus",
        "tempmail.dev",
        "tempmail.us",
        "trashmail.ws",
        "fakemailgenerator.com",
        "emailnax.com",
        "tempinbox.me",
        "1secmail.com",
        "1secmail.org",
        "1secmail.net",
        "by.privacy.net",
        "correotemporal.org",
        "cryptonet.top",
        "emltmp.com",
        "fivemail.de",
        "generator.email",
        "guerrillamail.info",
        "inboxbear.com",
        "luxusmail.org",
        "mailgg.net",
        "mailkept.com",
        "mfsa.ru",
        "muellmail.com",
        "nomail.xl.cx",
        "prtnx.com",
        "rcpt.at",
        "reddcoin2.com",
        "smashmail.de",
        "spamoff.de",
        "tempemail.info",
        "tempmail.it",
        "trash.me",
        "wegwerfmail.de",
        "wegwerfmail.net",
        "wegwerfmail.org",
        "wh4f.org",
        "xjoi.com",
        "yomail.info",
        "zeroe.ml",
        "zzrgg.com",

        // --- Russian/CIS disposable services ---
        "mailforspam.com",
        "cust.in",
        "grr.la",
        "dmarc.ro",
        "imgof.com",
        "insorg-mail.info",
        "llogin.ru",
        "mfsa.ru",
        "mfsa.info",

        // --- Additional high-confidence disposable domains ---
        "binkmail.com",
        "bobmail.info",
        "bodhi.lawlita.com",
        "bofthew.com",
        "boun.cr",
        "bouncr.com",
        "breakthru.com",
        "brefmail.com",
        "broadbandninja.com",
        "bsnow.net",
        "bugmenot.com",
        "bumpymail.com",
        "bund.us",
        "bundes-ede.de",
        "burnthespam.info",
        "buymoreplays.com",
        "buyusedlibrarybooks.org",
        "cachedot.net",
        "casualdx.com",
        "centermail.com",
        "centermail.net",
        "chammy.info",
        "cheatmail.de",
        "chogmail.com",
        "choicemail1.com",
        "clixser.com",
        "clrmail.com",
        "cmail.com",
        "cmail.net",
        "cmail.org",
        "cobamail.com",
        "consumerriot.com",
        "cool.fr.nf",
        "correo.blogos.net",
        "cosmorph.com",
        "courriel.fr.nf",
        "courrieltemporaire.com",
        "crapmail.org",
        "crazespaces.pw",
        "crossroadsmail.com",
        "cszbl.com",
        "cubiclink.com",
        "curryworld.de",
        "cuvox.de",
        "dacoolest.com",
        "dandikmail.com",
        "dayrep.com",
        "dbunker.com",
        "dcemail.com",
        "deadaddress.com",
        "deadfake.cf",
        "deadfake.ga",
        "deadfake.ml",
        "deadfake.tk",
        "deadspam.com",
        "deagot.com",
        "dealja.com",
        "despam.it",
        "despammed.com",
        "devnullmail.com",
        "dfgh.net",
        "digitalsanctuary.com",
        "dingbone.com",
        "dingfone.com",
        "disbox.net",
        "disbox.org",
    };

    /// <summary>
    /// Returns true if the domain is a known disposable/temporary email provider.
    /// Also checks subdomains — e.g., "sub.mailinator.com" matches "mailinator.com".
    /// </summary>
    public static bool IsDisposable(string domain)
    {
        if (string.IsNullOrWhiteSpace(domain))
            return false;

        domain = domain.Trim().ToLowerInvariant();

        // Direct match
        if (Domains.Contains(domain))
            return true;

        // Subdomain check: "anything.mailinator.com" should match "mailinator.com"
        var dotIndex = domain.IndexOf('.');
        while (dotIndex >= 0 && dotIndex < domain.Length - 1)
        {
            domain = domain[(dotIndex + 1)..];
            if (Domains.Contains(domain))
                return true;
            dotIndex = domain.IndexOf('.');
        }

        return false;
    }

    /// <summary>
    /// Returns the total count of known disposable domains (useful for health/stats).
    /// </summary>
    public static int Count => Domains.Count;
}
